FROM ipeddocker/dependencies:3.14.3

COPY iped/iped-3.14.3 /root/IPED/iped
COPY iped/mplayer /root/IPED/mplayer
COPY iped/optional_jars /root/IPED/optional_jars
COPY iped/regripper /root/IPED/regripper
COPY LocalConfig.txt /root/IPED/iped/LocalConfig.txt
WORKDIR /root/IPED/iped
