FROM ipeddocker/dependencies

COPY iped/iped-3.14.5 /root/IPED/iped
COPY iped/mplayer /root/IPED/mplayer
COPY iped/optional_jars /root/IPED/optional_jars
COPY iped/regripper /root/IPED/regripper
COPY LocalConfig.txt /root/IPED/iped/
COPY IPEDConfig.txt /root/IPED/iped/
COPY AdvancedConfig.txt /root/IPED/iped/conf/
WORKDIR /root/IPED/iped
