FROM ipeddocker/iped:dependencies 

WORKDIR /root/IPED/
RUN wget --progress=bar:force https://github.com/lfcnassif/IPED/releases/download/3.17.1/IPED-3.17.1.zip -O iped.zip
RUN unzip iped.zip && rm iped.zip && ln -s iped-3.17.1 iped
COPY LocalConfig.txt /root/IPED/iped/
COPY IPEDConfig.txt /root/IPED/iped/profiles/pt-BR/default/
COPY IPEDConfig.txt /root/IPED/iped/profiles/en/default/
COPY ./optional_jars/* /root/IPED/optional_jars/
# Copying custom profiles
# COPY ./fastrobust /root/IPED/iped/profiles/pt-BR/fastrobust
# COPY ./pedorobust /root/IPED/iped/profiles/pt-BR/pedorobust


WORKDIR /root/IPED/iped
