FROM nvidia/cuda:10.2-base

WORKDIR /root/pkgs
RUN apt-get update && apt-get install -y \
      git \
      build-essential \
      libafflib-dev zlib1g-dev libewf-dev unzip patch libssl-dev \
      autoconf automake autopoint libtool pkg-config yasm gettext wget \
      libaa1-dev libasound2-dev libcaca-dev libcdparanoia-dev libdca-dev \
      libdirectfb-dev libenca-dev libfontconfig1-dev libfreetype6-dev \
      libfribidi-dev libgif-dev libgl1-mesa-dev libjack-jackd2-dev libopenal1 libpulse-dev \
      libsdl1.2-dev libvdpau-dev libxinerama-dev libxv-dev libxvmc-dev libxxf86dga-dev \
      libxxf86vm-dev librtmp-dev libsctp-dev libass-dev libfaac-dev libsmbclient-dev libtheora-dev \
      libogg-dev libxvidcore-dev libspeex-dev libvpx-dev libdv4-dev \
      libopencore-amrnb-dev libopencore-amrwb-dev libmp3lame-dev liblivemedia-dev libtwolame-dev \
      libmad0-dev libgsm1-dev libbs2b-dev liblzo2-dev ladspa-sdk libfaad-dev \
      libmpg123-dev libopus-dev libbluray-dev libaacs-dev \
      libjpeg-dev \
      libtiff-dev \
      libpng-dev \
      libwmf-dev \
      libgif-dev \
      libheif-dev \
      libwebp-dev \
      librsvg2-dev \
      libopenexr-dev \
      vim \
      less\
      openjdk-8-jdk \
      unzip \
      openjfx=8u161-b12-1ubuntu2 \
      libopenjfx-java=8u161-b12-1ubuntu2 \
      libopenjfx-jni=8u161-b12-1ubuntu2 \
      libgl1-mesa-dri \
      libparse-win32registry-perl \
      tesseract-ocr tesseract-ocr-por tesseract-ocr-osd \
      && apt-get download ant && ls *.deb | awk '{system("dpkg-deb -x "$1" /")}' \
      && apt-get clean && rm -rf /var/lib/apt/lists/*


WORKDIR /opt
RUN git clone https://github.com/lfcnassif/sleuthkit-APFS \
    && cd /opt/sleuthkit-APFS/ \
    && ./bootstrap \ 
    && ./configure --prefix=/usr/ \
    && make && make install \
    && rm -rf /opt/sleuthkit-APFS/

WORKDIR /opt
RUN wget --progress=bar:force http://www.mplayerhq.hu/MPlayer/releases/MPlayer-1.4.tar.gz \
    && tar xvzf MPlayer-1.4.tar.gz \
    && cd /opt/MPlayer-1.4 \
    && ./configure --prefix=/usr \
    && make all install \
    && cd /usr/lib \
    && wget --progress=bar:force http://www.mplayerhq.hu/MPlayer/releases/codecs/all-20110131.tar.bz2 \
    && tar xvjf all-20110131.tar.bz2 && mv all-20110131 codecs && rm all-20110131.tar.bz2

WORKDIR /opt
RUN git clone https://github.com/libyal/libagdb.git \
    && cd /opt/libagdb \
    && ./synclibs.sh \
    && ./autogen.sh \    
    && ./configure --prefix=/usr \ 
    && make all install \
    && rm -rf /opt/libagdb

WORKDIR /opt
RUN git clone --branch="20191221" https://github.com/libyal/libevtx \
    && cd /opt/libevtx \ 
    && ./synclibs.sh \
    && ./autogen.sh \
    && ./configure --prefix=/usr \
    && make all install \
    && rm -rf /opt/libevtx

WORKDIR /opt
RUN git clone https://github.com/libyal/libevt \
    && cd /opt/libevt \
    && ./synclibs.sh \
    && ./autogen.sh \
    && ./configure --prefix=/usr \
    && make all install \
    && rm -rf /opt/libevt

WORKDIR /opt
RUN git clone https://github.com/libyal/libscca \
    && cd /opt/libscca \
    && ./synclibs.sh \
    && ./autogen.sh \
    && ./configure --prefix=/usr \
    && make all install \
    && rm -rf /opt/libscca

WORKDIR /opt
RUN git clone https://github.com/libyal/libesedb \
    && cd /opt/libesedb \
    && ./synclibs.sh \
    && ./autogen.sh \
    && ./configure --prefix=/usr \
    && make all install \
    && rm -rf /opt/libesedb

WORKDIR /opt
RUN git clone https://github.com/libyal/libpff \
    && cd /opt/libpff \
    && ./synclibs.sh \
    && ./autogen.sh \
    && ./configure --prefix=/usr \ 
    && make all install \
    && rm -rf /opt/libpff

WORKDIR /opt
RUN git clone https://github.com/libyal/libmsiecf \
    && cd /opt/libmsiecf \
    && ./synclibs.sh \
    && ./autogen.sh \
    && ./configure --prefix=/usr \
    && make all install \
    && rm -rf /opt/libmsiecf

WORKDIR /opt
RUN git clone https://github.com/abelcheung/rifiuti2 \
    && cd /opt/rifiuti2 \
    && autoreconf -f -i -v \
    && ./configure --prefix=/usr \
    && make all install \
    && rm -rf /opt/rifiuti2

WORKDIR /opt
RUN git clone --branch "7.0.8-14" https://github.com/ImageMagick/ImageMagick \
    && cd /opt/ImageMagick \
    && ./configure --prefix=/usr \
    && make all install \
    && rm -rf /opt/ImageMagick

ENV TZ=Brazil/East
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# Creating mplayer config
RUN mplayer

WORKDIR /root/IPED/
RUN wget --progress=bar:force https://github.com/lfcnassif/IPED/releases/download/3.17.1/IPED-3.17.1.zip -O iped.zip \
    && unzip iped.zip && rm iped.zip && ln -s iped-3.17.1 iped
# optional_jars will be a volume due its size
# COPY ./optional_jars/* ./
COPY LocalConfig.txt /root/IPED/iped/
COPY IPEDConfig.txt /root/IPED/iped/profiles/pt-BR/default/
COPY IPEDConfig.txt /root/IPED/iped/profiles/en/default/
# Copying custom profiles
# COPY ./fastrobust /root/IPED/iped/profiles/pt-BR/fastrobust
# COPY ./pedorobust /root/IPED/iped/profiles/pt-BR/pedorobust


ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/
ENV JDK_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV JRE_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/
ENV J2REDIR=/usr/lib/jvm/java-8-openjdk-amd64/jre/
ENV J2SDKDIR=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:$PATH

WORKDIR /root/IPED/iped
