name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
      
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      
    - name: pull latest (for cache)
      run: docker pull ipeddocker/iped:dependencies && docker pull ipeddocker/iped:processor && docker pull ipeddocker/iped:latest || echo could not pull
      

    - name: Docker build dependencies
      run: docker build --cache-from ipeddocker/iped:dependencies . -f Dockerfile.dependencies -t ipeddocker/iped:dependencies

    - name: Docker push dependencies (if master)
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:dependencies


    - name: Docker build processor
      run: docker build --cache-from ipeddocker/iped:processor . -f Dockerfile.processor -t ipeddocker/iped:processor

    - name: Docker push processor (if master)
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:processor
      

    - name: Docker build latest
      run: docker build --cache-from ipeddocker/iped:latest . -t ipeddocker/iped:latest
      
    - name: Docker push latest (if master)
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:latest


    - name: Docker push - semver
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker tag ipeddocker/iped:latest ipeddocker/iped:${GITHUB_REF#refs/tags/}
        docker tag ipeddocker/iped:processor ipeddocker/iped:processor_${GITHUB_REF#refs/tags/} 
        docker tag ipeddocker/iped:dependencies ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/} 
        docker push ipeddocker/iped:${GITHUB_REF#refs/tags/}
        docker push ipeddocker/iped:processor_${GITHUB_REF#refs/tags/}
        docker push ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/}
