name: CI/CD

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

#    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    if: startsWith(github.ref, 'refs/tags/iped_') 
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1      
      
    - name: Docker login      
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}  

#
# using classic build on dependencies, because is the only way to cache now.
#
    - name: Docker pull dependecies-RELEASE 
      run: docker pull ipeddocker/iped:dependencies || echo could not pull

    - name: Docker build dependecies-RELEASE 
      run: docker build --cache-from ipeddocker/iped:dependencies . -f Dockerfile.dependencies -t ipeddocker/iped:dependencies

    - name: Docker push dependecies-RELEASE 
      run: |
        docker tag ipeddocker/iped:dependencies ipeddocker/iped:dependencies_${{ github.ref_name }}
        docker push ipeddocker/iped:dependencies 
        docker push ipeddocker/iped:dependencies_${{ github.ref_name }}


    - name: Docker build processor-RELEASE 
      uses: docker/build-push-action@v4      
      with:
        context: .
        file: Dockerfile.processor
        tags: | 
          ipeddocker/iped:processor
          ipeddocker/iped:processor_${{ github.ref_name }}
        push: true 
        build-args: |
          "SNAPSHOT=false"
        secrets: |
          "ACTION_GH_TOKEN=${{ secrets.ACTION_GH_TOKEN }}"


    - name: Docker build iped-RELEASE 
      uses: docker/build-push-action@v4      
      with:
        context: .        
        tags: | 
          ipeddocker/iped:latest
          ipeddocker/iped:${{ github.ref_name }}
        push: true 
