name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
      
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      
    #- name: pull latest (for cache)
    #  run: | 
    #    docker pull ipeddocker/iped:dependencies  
    #    docker pull ipeddocker/iped:processor 
    #    docker pull ipeddocker/iped:latest 
    #    docker pull ipeddocker/iped:dependencies-cuda 
    #    docker pull ipeddocker/iped:processor-cuda 
      
      

    #- name: Docker build dependencies
    #  run: docker build --cache-from ipeddocker/iped:dependencies . -f Dockerfile.dependencies -t ipeddocker/iped:dependencies

    #- name: Docker push dependencies (if master)
    #  if: github.ref == 'refs/heads/master'
    #  run: docker push ipeddocker/iped:dependencies

    #- name: Docker build processor
    #  run: docker build --cache-from ipeddocker/iped:processor . -f Dockerfile.processor -t ipeddocker/iped:processor

    #- name: Docker push processor (if master)
    #  if: github.ref == 'refs/heads/master'
    #  run: docker push ipeddocker/iped:processor      

    #- name: Docker build latest
    #  run: docker build --cache-from ipeddocker/iped:latest . -t ipeddocker/iped:latest
      
    #- name: Docker push latest (if master)
    #  if: github.ref == 'refs/heads/master'
    #  run: docker push ipeddocker/iped:latest 

    #- name: Docker push - semver
    #  if: startsWith(github.ref, 'refs/tags/')
    #  run: |
    #    docker tag ipeddocker/iped:latest ipeddocker/iped:${GITHUB_REF#refs/tags/}
    #    docker tag ipeddocker/iped:processor ipeddocker/iped:processor_${GITHUB_REF#refs/tags/} 
    #    docker tag ipeddocker/iped:dependencies ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/} 
    #    docker push ipeddocker/iped:${GITHUB_REF#refs/tags/}
    #    docker push ipeddocker/iped:processor_${GITHUB_REF#refs/tags/}
    #    docker push ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/} 
    #    docker rmi ipeddocker/iped:dependencies ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/}
    #    docker rmi ipeddocker/iped:processor ipeddocker/iped:processor_${GITHUB_REF#refs/tags/}
    #    docker rmi ipeddocker/iped:latest ipeddocker/iped:${GITHUB_REF#refs/tags/}



    - name: Docker build transcriptor-CUDA      
      #run: docker build --cache-from ipeddocker/iped:transcriptor . -f Dockerfile.transcriptor-cuda -t ipeddocker/iped:transcriptor-cuda
      run: docker build . -f Dockerfile.transcriptor-cuda -t ipeddocker/iped:transcriptor

    - name: Docker push transcriptor-CUDA (if master)
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:transcriptor      

    - name: Docker push transcriptor-CUDA - semver
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker tag ipeddocker/iped:transcriptor ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/} 
        docker push ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/}  
        docker rmi ipeddocker/iped:transcriptor ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/} 



    - name: Docker build dependencies-CUDA
      #run: docker build --cache-from ipeddocker/iped:dependencies . -f Dockerfile.dependencies-cuda -t ipeddocker/iped:dependencies
      run: docker build . -f Dockerfile.dependencies-cuda -t ipeddocker/iped:dependencies

    - name: Docker push dependencies-CUDA (if master)
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:dependencies

    - name: Docker build processor-CUDA      
      # run: docker build --cache-from ipeddocker/iped:processor-cuda . -f Dockerfile.processor-cuda -t ipeddocker/iped:processor
      run: docker build . -f Dockerfile.processor-cuda -t ipeddocker/iped:processor

    - name: Docker push processor-CUDA (if master)
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:processor

    - name: Docker push CUDA versions - semver
      if: startsWith(github.ref, 'refs/tags/')
      run: |   
        docker tag ipeddocker/iped:processor ipeddocker/iped:processor_${GITHUB_REF#refs/tags/} 
        docker tag ipeddocker/iped:dependencies ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/}   
        docker push ipeddocker/iped:processor_${GITHUB_REF#refs/tags/}
        docker push ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/}
