name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
      
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      
    

    - name: get JSON for snapshot artifact
      id: get_snapshot
      run: |
        snapshotJSON=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/sepinf-inc/IPED/actions/artifacts?per_page=1)         
        snapshotJSON="${snapshotJSON//'%'/'\\%'}"
        snapshotJSON="${snapshotJSON//$'\n'/' '}"
        snapshotJSON="${snapshotJSON//$'\r'/''}"
        snapshotJSON="${snapshotJSON//\"/\\\"}"
        echo "SNAPSHOT_JSON=$snapshotJSON" >> $GITHUB_OUTPUT
      #outputs:
      #  snapshot: ${{ steps.get_snapshot.outputs.SNAPSHOT_JSON }}

    - name: download snapshot
      run: |
        url="${{ fromJson( steps.get_snapshot.outputs.SNAPSHOT_JSON ).artifacts.*.archive_download_url }}"
        curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ACTION_GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" --output iped.zip ${url}


    - name: Docker build transcriptor-CUDA      
      run: |
        docker pull ipeddocker/iped:transcriptor
        docker build --cache-from ipeddocker/iped:transcriptor . -f Dockerfile.transcriptor-cuda -t ipeddocker/iped:transcriptor --build-arg SNAPSHOT=true

    - name: Docker push transcriptor-CUDA (if master)
      if: github.ref == 'refs/heads/master'
      run: | 
        docker push ipeddocker/iped:transcriptor
        docker rmi ipeddocker/iped:transcriptor

    - name: Docker push transcriptor-CUDA - (if release)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker tag ipeddocker/iped:transcriptor ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/} 
        docker push ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/}  
        docker rmi ipeddocker/iped:transcriptor ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/}


    - name: Docker build dependencies-CUDA
      run: |
        docker pull ipeddocker/iped:dependencies
        docker build --cache-from ipeddocker/iped:dependencies . -f Dockerfile.dependencies-cuda -t ipeddocker/iped:dependencies
      
    - name: Docker push dependencies-CUDA (if master)
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:dependencies

    - name: Docker build processor-CUDA      
      run: |
        docker pull ipeddocker/iped:processor
        docker build --cache-from ipeddocker/iped:processor . -f Dockerfile.processor-cuda -t ipeddocker/iped:processor
      
    - name: Docker push processor-CUDA (if master)
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:processor

    - name: Docker push CUDA versions - (if release)
      if: startsWith(github.ref, 'refs/tags/')
      run: |   
        docker tag ipeddocker/iped:processor ipeddocker/iped:processor_${GITHUB_REF#refs/tags/} 
        docker tag ipeddocker/iped:dependencies ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/}   
        docker push ipeddocker/iped:processor_${GITHUB_REF#refs/tags/}
        docker push ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/}
