name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    steps:
    
      
    - name: Docker login
      uses: actions/checkout@v3
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
       
    - name: Docker build transcriptor-CUDA 
      uses: docker/build-push-action@v4
      context: .
      file: Dockerfile.transcriptor-cuda
      tags: ipeddocker/iped:transcriptor 
      cache-from: |
        ipeddocker/iped:transcriptor   
      push: true  
      build-args: |
        "SNAPSHOT=true"
      with:
        secrets: |
          "ACTION_GH_TOKEN=${{ secrets.ACTION_GH_TOKEN }}"

#     run: |
#        docker pull ipeddocker/iped:transcriptor
#        docker build --cache-from ipeddocker/iped:transcriptor . -f Dockerfile.transcriptor-cuda -t ipeddocker/iped:transcriptor --build-arg 
 
#    - name: Docker push transcriptor-CUDA (if master)
#      if: github.ref == 'refs/heads/master'
#      run: | 
#        docker push ipeddocker/iped:transcriptor
#        docker rmi ipeddocker/iped:transcriptor

    - name: Docker push transcriptor-CUDA - (if release)
      uses: actions/checkout@v3
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker tag ipeddocker/iped:transcriptor ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/} 
        docker push ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/}  
        docker rmi ipeddocker/iped:transcriptor ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/}



    - name: Docker build dependencies-CUDA
      uses: actions/checkout@v3
      run: |
        docker pull ipeddocker/iped:dependencies
        docker build --cache-from ipeddocker/iped:dependencies . -f Dockerfile.dependencies-cuda -t ipeddocker/iped:dependencies
      
    - name: Docker push dependencies-CUDA (if master)
      uses: actions/checkout@v3
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:dependencies

    - name: Docker build processor-CUDA      
      uses: actions/checkout@v3
      run: |
        docker pull ipeddocker/iped:processor
        docker build --cache-from ipeddocker/iped:processor . -f Dockerfile.processor-cuda -t ipeddocker/iped:processor
      
    - name: Docker push processor-CUDA (if master)
      uses: actions/checkout@v3
      if: github.ref == 'refs/heads/master'
      run: docker push ipeddocker/iped:processor

    - name: Docker push CUDA versions - (if release)
      uses: actions/checkout@v3
      if: startsWith(github.ref, 'refs/tags/')
      run: |   
        docker tag ipeddocker/iped:processor ipeddocker/iped:processor_${GITHUB_REF#refs/tags/} 
        docker tag ipeddocker/iped:dependencies ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/}   
        docker push ipeddocker/iped:processor_${GITHUB_REF#refs/tags/}
        docker push ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/}
