name: CI/CD

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker login      
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
   
    - name: Docker build transcriptor-SNAPSHOT 
      uses: docker/build-push-action@v4      
      with:
        context: .
        file: Dockerfile.transcriptor-cuda
        tags: ipeddocker/iped:transcriptor_snapshot
        cache-from: |
          type=registry,ref=ipeddocker/iped:transcriptor_snapshot
          type=registry,ref=ipeddocker/iped:transcriptor
        push: true 
        build-args: |
          "SNAPSHOT=true"
        secrets: |
          "ACTION_GH_TOKEN=${{ secrets.ACTION_GH_TOKEN }}"
    
    - name: Docker build transcriptor-RELEASE 
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v4      
      with:
        context: .
        file: Dockerfile.transcriptor-cuda
        tags: | 
          ipeddocker/iped:transcriptor
          ipeddocker/iped:transcriptor_${GITHUB_REF#refs/tags/}
        cache-from: type=registry,ref=ipeddocker/iped:transcriptor
        push: true 
        secrets: |
          "ACTION_GH_TOKEN=${{ secrets.ACTION_GH_TOKEN }}"

    # transcriptor base image is different from other steps, so
    # we dont need its image on the server
    # this step is to avoid disk space problems on next steps
    - name: Cleaning TRANSCRIPTION docker environment 
      run: docker image prune -a -f


    - name: Docker build dependecies-RELEASE 
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v4      
      with:
        context: .
        file: Dockerfile.dependencies-cuda
        tags: | 
          ipeddocker/iped:dependencies
          ipeddocker/iped:dependencies_${GITHUB_REF#refs/tags/}
        cache-from: type=registry,ref=ipeddocker/iped:dependencies
        push: true 
      
    - name: Docker build processor-RELEASE 
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v4      
      with:
        context: .
        file: Dockerfile.processor-cuda
        tags: | 
          ipeddocker/iped:processor
          ipeddocker/iped:processor_${GITHUB_REF#refs/tags/}
        cache-from: type=registry,ref=ipeddocker/iped:processor
        push: true 

    - name: Docker build iped-RELEASE 
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v4      
      with:
        context: .        
        tags: | 
          ipeddocker/iped:latest
          ipeddocker/iped:${GITHUB_REF#refs/tags/}
        cache-from: type=registry,ref=ipeddocker/iped:latest
        push: true 
