name: CI/CD

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

#    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
    if: startsWith(github.ref, 'refs/tags/') 
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1      
      
    - name: Docker login      
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}  
    

    - name: Docker build transcriptor
      if: startsWith(github.ref, 'refs/tags/') 
      uses: docker/build-push-action@v4      
      with:
        context: .
        file: Dockerfile.transcriptor
        tags: |
          ipeddocker/iped:transcriptor
          ipeddocker/iped:transcriptor_${{ github.ref_name }}
        cache-from: type=registry,ref=docker.io/ipeddocker/iped:transcriptor_cache
        cache-to: type=registry,ref=docker.io/ipeddocker/iped:transcriptor_cache,mode=max
        push: true 
        build-args: |
          "SNAPSHOT=true"
        secrets: |
          "ACTION_GH_TOKEN=${{ secrets.ACTION_GH_TOKEN }}"

    # transcriptor base image is different from other steps, so
    # we dont need its image on the server
    # this step is to avoid disk space problems on next steps
    - name: Cleaning TRANSCRIPTION docker environment 
      run: docker buildx prune -a -f

    - name: Docker build dependecies-RELEASE 
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v4      
      with:
        context: .
        file: Dockerfile.dependencies
        tags: | 
          ipeddocker/iped:dependencies
          ipeddocker/iped:dependencies_${{ github.ref_name }}
        cache-from: type=registry,ref=docker.io/ipeddocker/iped:dependencies_cache
        cache-to: type=registry,ref=docker.io/ipeddocker/iped:dependencies_cache,mode=max
        push: true 
      
    - name: Docker build processor-RELEASE 
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v4      
      with:
        context: .
        file: Dockerfile.processor
        tags: | 
          ipeddocker/iped:processor
          ipeddocker/iped:processor_${{ github.ref_name }}
        cache-from: type=registry,ref=docker.io/ipeddocker/iped:processor_cache
        cache-to: type=registry,ref=docker.io/ipeddocker/iped:processor_cache,mode=max
        push: true 

    - name: Docker build iped-RELEASE 
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v4      
      with:
        context: .        
        tags: | 
          ipeddocker/iped:latest
          ipeddocker/iped:${{ github.ref_name }}
        cache-from: type=registry,ref=docker.io/ipeddocker/iped:latest_cache
        cache-to: type=registry,ref=docker.io/ipeddocker/iped:latest_cache,mode=max
        push: true 
